name: 07 - Using Expressions

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[debug] Print when triggered from main"
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug && github.ref == 'refs/heads/main' }}
        run: echo "I was triggered from main"

      - name: "Greeting"
        run: echo "Hello, world"

    run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
